server:
  port: 2639
  address: 0.0.0.0
  http2:
    enabled: true

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "halflife3isnotreal"
    sources:
      youtube: false # Handled by youtube-plugin
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 100
    playerUpdateInterval: 3
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - TVHTML5_SIMPLY
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN:}"
      skipInitialization: true
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
    spotify:
      clientId: "" # Optional: add your Spotify Client ID
      clientSecret: "" # Optional: add your Spotify Client Secret
      countryCode: "TH"
      playlistLoadLimit: 100
      albumLoadLimit: 50

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/lavalink.log
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: false
    maxPayloadLength: 10000
