services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: focalors-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
      - ./logs:/opt/Lavalink/logs
    ports:
      - "2639:2639"
    networks:
      - focalors-net

networks:
  focalors-net:
    driver: bridge
